server:
  # Возможно, у вас нет обычного Tomcat, если сервис работает только как gRPC,
  # но если всё же нужен Spring Web, укажите порт (или уберите, если не нужен).
  port: 8081

grpc:
  server:
    port: 9090         # Domain-сервис будет слушать gRPC здесь

spring:
  data:
    mongodb:
      # Подключение к локально запущенному Mongo
      uri: mongodb://localhost:27017/newdb

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
