server:
  port: 8081

grpc:
  server:
    port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: newdb
      username: root
      password: example

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: vhost

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
